### ISSUE TITLE
unmapAllExcept does not unmap number keys

### ISSUE THREAD

**Issue by usommerl** [brookhong/Surfingkeys#1002]
## Version
SurfingKeys: 0.9.45
Browser: Chromium 74.0.3729.169, Linux

## Minimal example
Use this line as your SurfingKeys configuration: `unmapAllExcept([], /example\.com/i);`

#### Expected result: 
Default mappings from SurfingKeys are unmapped on domain example.com
#### Actual result: 
SurfingKeys tries to display a mapping hint when a number key is pressed and does not relay the key event to the underlying web application

## Practical background
I want to use SurfingKeys in conjunction with Atlassian Jira. Jira defines shortcuts `1`, `2`, `3` to switch between backlog, board and reports. I know that I can disable SurfingKeys completely on the respective domain, but I would like to keep a couple of mappings from SurfingKeys and use the Jira keys as well.

**Comment by brookhong** [comment]
Thanks, fixed in 0.9.49

**Comment by usommerl** [comment]
Thanks for looking into this! 

Unfortunately, your change only fixes the issue for the minimal example I provided:
:heavy_check_mark: `unmapAllExcept([], /example\.com/i);`

It does not unmap the number keys when I use a non-empty list as argument:
:x: `unmapAllExcept(['f'], /example\.com/i);`

I'm currently using the following versions
```
SurfingKeys: 0.9.50
Browser: Chromium 78.0.3904.70, Linux
```

**Comment by usommerl** [comment]
Please consider reopening this issue as it is not fixed. (See my previous comment)

**Comment by Dima-369** [comment]
@usommerl you could use `settings.digitForRepeat = false;` which disables the digits entirely. I never use them, so this is a nice fix for me.

But you are correct, this bug still occurs.

**Comment by usommerl** [comment]
@Dima-369 I wasn't aware of the `digitForRepeat` setting. I don't use repeats either, so this is a nice workaround. Thank You!

**Comment by plt3** [comment]
Just ran into this problem as well, it's a shame to have to disable `digitForRepeat` globally to be able to unmap them just for one website. Looks like `api.unmap` also doesn't work for numbers according to #1316 and my experience...
