### ISSUE TITLE
Disabling pdf viewer doesn't not work properly

### ISSUE THREAD

**Issue by MuseBoy** [brookhong/Surfingkeys#1119]
## Error details

1. with surfingkeys enabled, and pdf viewer disabled, opening pdf in chrome will result in an empty page.
2. with surfingkeys disabled, opening pdf in chrome is ok.

SurfingKeys: 0.9.56

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

URL: <file:///C:/xxx/mathematical%20logic/proof%20theory/handbook-of-proof-theory.pdf>

**Comment by vmasrani** [comment]
Bump -  this is causing me to have to disable surfingkeys :(

**Comment by brookhong** [comment]
Fixed in 0.9.57, please have a try.

**Comment by hzfmer** [comment]
Still cannot open pdf in Chrome 79.0.3945.117.

Only a gray page is shown, while it works after turning Surfingkeys off and using the original PDF viewer.

It is impossible to use any hotkeys on this blank page, so `;s` doesn't work to switch PDF viewer, which makes it really inconvenient.

**Comment by gyli** [comment]
@brookhong Same to me. Issue still exists with version 0.9.57
