### ISSUE TITLE
`settings.blocklistPatterns` is not working

### ISSUE THREAD

**Issue by shirakiya** [brookhong/Surfingkeys#2154]
## Error details

SurfingKeys: 1.17.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context
`settings.blocklistPatterns` is not working.

[My settings](https://github.com/shirakiya/dotfiles/blob/7c6fd79e030c53b70531e2ae975f7d18e7f8b4fa/surfingkeys.js) had worked yesterday. However, SurfingKeys has not been disabled on `https://mail.google.com/...` after updating Google Chrome.

**Comment by clarkwang** [comment]
Same here.

**Comment by brookhong** [comment]
Fixed in 1.17.1.

**Comment by shirakiya** [comment]
@brookhong 
Thanks for your announce. I'm already on 1.17.1 and it has still not been working.
https://github.com/brookhong/Surfingkeys/commit/965301c079852f9d310145d823628d107e940588 is the new commit in 1.17.1, but it seems it does not contain fixes for this issue.
