### ISSUE TITLE
It is necessary to press the close tab key twice

### ISSUE THREAD

**Issue by ncaq** [brookhong/Surfingkeys#2203]
## Error details

SurfingKeys: 1.17.4

Browser: Firefox 132.0.1, Windows 11 Pro 24H2

## Context

When I booted up my PC today, the key to close tabs assigned to Surfingkeys had to be pressed twice for it to work.
I suspect this is because of the recent release of the Surfingkeys update.
I have not received any error messages.
The Surfingkeys configuration is as follows.

``` js
mapkey("w", "#3Close current tab", () => {
  RUNTIME("closeTab");
});
mapkey("q", "#3Close current tab", () => {
  RUNTIME("closeTab");
});
```

The full config is <https://github.com/ncaq/surfingkeys-config/blob/master/setting.js>

**Comment by dhottinger** [comment]
SurfingKeys: 1.17.4

Browser: Firefox 132.0.1, Linux

Same here. Not just `closeTab`, also other actions like `nextTab`/`previousTab` need to be invoked twice.

E.g.
```
api.mapkey('gt', '#3Go one tab right', function() {
  api.RUNTIME('nextTab');
}, {repeatIgnore: true});
```

Interestingly, after pressing any such key (resulting in no action) on a newly loaded page, things start to work without requiring repeat.

Say I press `gt` to switch to the next tap (noting happens). The I press `gt` again (now it works). I go back to the tab and press the key to close the tab (works first try).

Looks like the first invocation of `RUNTIME()` goes to `/dev/null`. Other key mappings that do other things (e.g. call `api.Front.openOmnibar()`) work the first time.

**Comment by Madd0g** [comment]
someone mentioned that if you just want the action on another key - you can use `map()` and thus avoid this need of running things twice.

it's not ideal, but I changed my code around a little and it was a good enough workaround.

**Comment by brookhong** [comment]
Fixed in 1.17.5.

**Comment by petobens** [comment]
@ncaq is this working for you? For me @brookhong I'm still seeing  this issue in 1.17.5 when using the map reported here: https://github.com/brookhong/Surfingkeys/issues/2169#issuecomment-2423909244

**Comment by dhottinger** [comment]
Working for me now: Firefox 132.0.2 and Surfingkeys 1.17.5

Also fixed broken repeat count. Needs reload of all tabs after upgrade.

**Comment by ncaq** [comment]
It is working for me.
