### ISSUE TITLE
ZQ Quit Bug - doesn't support multiple Chrome Windows

### ISSUE THREAD

**Issue by AlexIvasi** [brookhong/Surfingkeys#23]
Hi - here is another bug 
ZQ Quit Bug - doesn't support multiple Chrome Windows

Steps to reproduce:
1. Open e.g. 2 Chrome windows with tabs
2. Press ZQ Quit - to Exit Chrome browser 
2.1 Browser is closed now no windows on you screen (work as designed)
3. Now start your Chrome 
4. Bug - it would restore only 1 Chrome Window while second vanishes .... 

Thank you!

**Comment by brookhong** [comment]
Fixed in 0.3.0.

**Comment by AlexIvasi** [comment]
Still doesn't work for me ... the first Window is saved - whereas the second is not recovered on startup (but it can be due to another extensions like Tabs Outliner) that can affect normal behavior on session restore state - so not sure on 100%

Can anyone retest it in their environment ?

**Comment by brookhong** [comment]
Please `ZZ` first to overwrite the LAST session, as sessions are saved in a little different way than before this release.

PS: what's your OS?

**Comment by AlexIvasi** [comment]
Hi Brook - it still doesn't work with your suggestion - please, check below test results.


Priority that issue is low as we do have a work around to use Chrome's native function - thought it will be cool to fix that.
Many thanks in advance. 

-----------
Test 1
-----------
Surfing keys 
ZZ -> then start Google Chrome - doesn't work (restores only one window (should restore 2))
ZZ then ZQ -> then start Google Chrome - doesn't work (restores only one window (should restore 2))
Same as above with disabled Tabs Outliner extension - also doesn't work.

-----------
Test 2
-----------
Tabs Ouliner 
Using Tabs Outliner function to close Chrome
Session restore (doesn't work as well)

-----------
Test 3
-----------
Google Chrome 
Menu -> Exit or Ctrl + Shift + Q (Chrome's native function)
Works - i.e. restarts 2 Windows on start with anabled extensions (SurfingKeys + Tabs Outliner)


Conclussion:
Session restore works only with Chrome's native Ctrl + Shift + Q function
Windows 7 Enterprise 64 bit

**Comment by brookhong** [comment]
Don't you use `ZR` to restore session?

The LAST session is not restored automatically, you must press `ZR` to restore.

**Comment by AlexIvasi** [comment]
Hi Brook - yeah good point - I didn't know that it doesn't restore it automatically - so now with ZR it restores the session - BUT here is another bug ...

It restores second Window 2 - fine 
But with the Window 1 (first Window it adds a copy of each opened tab i.e. duplicates the tabs)
So imagine you had tabs x1 x2 x3 x4 x5 in your Window 1
Thus after restoring with ZR you get the following i.e. instead of 5 tabs -> 10 tabs
x1 x2 x3 x4 x5 x1 x2 x3 x4 x5 

thanks

**Comment by brookhong** [comment]
Yes, that is by-design.

`ZR` will just restore the URLs from saved session named LAST, it would not close current tabs.

**Comment by AlexIvasi** [comment]
Thanks for explanation. 
Then it can be considered as closed! as it is not a bug but a standard behavior of Google session restore.

Many thanks for your input Brook.
