### ISSUE TITLE
ask for “insert mode” to temporary disable surfingkey

### ISSUE THREAD

**Issue by yech1990** [brookhong/Surfingkeys#31]
this function can simply be achieved by press 'i' key, and press 'Esc' to recover.

**Comment by yech1990** [comment]
I also want to know how to disable certain key in a web page permanently.

**Comment by brookhong** [comment]
Click on the icon of Surfingkeys in toolbar to select `Disable Surfingkeys on this domain`.

**Comment by yech1990** [comment]
how about the temporary mode

**Comment by brookhong** [comment]
Fixed in 0.3.2, add `alt-s` as [hot key to toggle Surfingkeys](https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys).

**Comment by yech1990** [comment]
#### ``Disable Surfingkeys`` does not work properly!!!

when i press the disable surfing key on a webpage, surfingkeys will be off globally

**Comment by yech1990** [comment]
Although you spend lots of effort to improve sufingkey, plenty of bugs still exist. 
such as,
- The settings lost occasionally
- Once the focus enter a input box, it's impossible to jump out by pressing ecs bottom, unless I press enter to submit. //google search

**Comment by brookhong** [comment]
When Surfingkeys is turned off, all mappings stop working except the hotkey, but only for the site, what do you mean by `globally`?

**Comment by brookhong** [comment]
I did not see any issue of settings lost, could you please list your steps to reproduce? And for input box on google search, I can escape from the input focus by `esc` key.
