### ISSUE TITLE
Lose settings after several days

### ISSUE THREAD

**Issue by nubes** [brookhong/Surfingkeys#40]
I met this problems several times. And I tried to unmap `sr` to avoid resetting. No ideas about the reason.

**Comment by yech1990** [comment]
I met the same problem too.

**Comment by brookhong** [comment]
Thanks guys.

Fixed in 0.3.4

**Comment by nubes** [comment]
The bug remains. It maybe related to  `chrome-storage-local` or `chrome-storage-sync`.

**Comment by yech1990** [comment]
I don't think this problem is fixed. The latest version lost configuration frequently and unable to sync between any device.
