### ISSUE TITLE
In Gmail "Label" functionality lost auto focus after Version: 0.9.2

### ISSUE THREAD

**Issue by bojanjovicic** [brookhong/Surfingkeys#445]
In Gmail where Surfing Keys was used with **unmapAllExcept** after Version: 0.9.2 (Updated: August 14, 2017) Label functionality stopped getting auto focus. By using mouse it is kind of random (not always happening) but with keyboard (press l) it is always:

![capture](https://user-images.githubusercontent.com/4491442/29290113-3a7a272a-813f-11e7-8f35-3092ccad1bca.PNG)

Here is my unmap:
`unmapAllExcept(['<Ctrl-o>', '<Ctrl-r>', '<Ctrl-d>'], /mail\.google\.com/i); // Clear all keyboard mappings for Gmail except the ones listed (Ctrl-d is my mapping for a custom Javascript function for Gmail search by subject)
`

**Comment by bojanjovicic** [comment]
Potentially related to #447 (Google绘图中禁用扩展后依然有冲突)

**Comment by brookhong** [comment]
Yes, you're right.

This issue has same cause with #447.

**Comment by brookhong** [comment]
Fixed in 0.9.3.

**Comment by bojanjovicic** [comment]
Thank you very much @brookhong :1st_place_medal:

**Comment by bojanjovicic** [comment]
Hi @brookhong ,
I am not sure, but for me at least it appears that the issue still remains with version 0.9.3.
In order to help reproduce I created a video (sorry for flv to gif conversion), or opening google.com with SurfingKeys on without autofocus and then with autofocus. In Gmail it doesn't have autofocus still in combination with unmapAll 
Here is the video, but if more data is needed, don't hesitate to ask me (if some debug mode, etc. I know my basic way around JavaScript as language, but don't have experience with debugging addons, etc):
![2017-08-27-07-42-57](https://user-images.githubusercontent.com/4491442/29747448-dfcc79c4-8afb-11e7-8de4-bb7602e23b05.gif)

**Comment by jaredbidlow** [comment]
@bojanjovicic you noted that "Ctrl-d is my mapping for a custom Javascript function for Gmail search by subject". Can you share this code?

**Comment by bojanjovicic** [comment]
Hi @jaredbidlow ,
Here it is, but maybe too much customized for my purposes:
```
mapkey('<Ctrl-d>', 'Go down (Ctrl + D) to original conversation', function() {
    var title = document.title;
	title = clearTitle(title).replace("Notification: ", "");
	
	if (title.indexOf(" - #BRobot @ ") == -1)
	{
	    if (title.indexOf("... @ ") != -1)
	    {
		    title = title.substring(0, title.indexOf("... @ "));
            var lastIndex = title.lastIndexOf(" ");
            title = title.substring(0, lastIndex);
	    }
	}
	else
	{
	    title = title.substring(0, title.indexOf(" - #BRobot @ ")); 
	}

	var targetUrl = document.URL.substring(0, 33) + '#search/subject:"' + encodeURIComponent(title) + '"';
    window.location = targetUrl;
});
```
