### ISSUE TITLE
Add ability to edit CSS

### ISSUE THREAD

**Issue by brandenbyers** [brookhong/Surfingkeys#58]
Would it be possible to add the ability to edit the CSS displayed when typing "f" to open a link? Vimium and cVim both offer this feature. Is this something that I can already do? Or is this something you would consider adding in the future?

**Comment by brookhong** [comment]
I committed the change https://github.com/brookhong/Surfingkeys/commit/b9e2d372ecc17274a6b1f97ba55dcad156185f49 to achieve that.

For example, add below line into your settings:

    Hints.style("border: solid 3px #C38A22; color:red;");

Will release in next version.

**Comment by brookhong** [comment]
released in 0.4.0

**Comment by yech1990** [comment]
still unable to edit visual mode hints after pressing `v` key.
